spring.application.name=Portfolio-production

# Configurações de Banco de Dados de Produção
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://atb-db-postgres:5432/portfolio_agenciatelabranca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postdba}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Segurança
jwt.secret=${JWT_SECRET:ueQ4/xmGvHABx2E/weYGSGooPWYzncFgp29+FvqugBu3+a5eV7327CNQA8KkssEn9xEVY4k2PqWwK+rJ0HGUnw==}
jwt.expiration=86400000

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
