version: '3.8'

services:
  site-principal-atb-frontend:
    image: agenciatelabranca/site-principal-atb-frontend:latest
    container_name: site-principal-atb-frontend
    ports:
      - "3001:80"
    networks:
      infra_network:
        aliases:
          - frontend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  site-principal-atb-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: site-principal-atb-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_SITE_PRINCIPAL_TOKEN}
    networks:
      - infra_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  infra_network:
    external: true
    name: infra_default
