version: '3.8'

services:
  portfolio-frontend:
    image: agenciatelabranca/portfolio-frontend:latest
    container_name: portfolio-frontend-v2
    ports:
      - "3001:80"
    networks:
      infra_network:
        aliases:
          - frontend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portfolio-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: portfolio-tunnel-v2
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_PORTFOLIO_TOKEN}
    networks:
      - infra_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  infra_network:
    external: true
    name: infra_default
