services:
  frontend:
    build: .
    container_name: portfolio-frontend
    environment:
      - TZ=America/Sao_Paulo
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - TUNNEL_TOKEN=${CLOUDFLARE_SITE_TOKEN:-${TUNNEL_TOKEN:-}}
    command: tunnel run --token ${CLOUDFLARE_SITE_TOKEN:-${TUNNEL_TOKEN:-}}
